#!/bin/bash
# Begin libexec/fix-markdown

#---
## Fix Markdown file contents
## @Globals PROJECT_HOME_DIR project home directory
#---
function fix-markdown() {
  local MARKDOWN_DIR="${MARKDOWN_DIR:="$PROJECT_HOME_DIR/src/markdown"}"
  local SPEAKERS="${SPEAKERS:="$PROJECT_HOME_DIR/share/speakers"}"

  local SPEAKER
  awk -F, 'NF >= 4 && $2 != 0 { print $3 }' "$SPEAKERS" |
  while read SPEAKER
  do
    sed -i "s/^$SPEAKER[:：] *$/$SPEAKER（通常）：/" "$MARKDOWN_DIR"/*-*-*.md
  done

  local PREV_CHAPTER
  local PREV_STORY
  local PREV_TITLE
  local PREV_MARKDOWN
  local MARKDOWN
  for MARKDOWN in "$MARKDOWN_DIR"/*-*-*.md
  do
    local CHAPTER="$(awk -F- '{print $1}' <<< "${MARKDOWN##*/}" | sed 's/^0*//')"
    local STORY="$(awk -F- '{print $2}' <<< "${MARKDOWN##*/}" | sed 's/^0*//')"
    local TITLE="$(grep -m1 '^title=' "$MARKDOWN" | awk -F= '{ print $2 }')"
    sed -i \
      -e "s/^chapter=.*/chapter=$CHAPTER/" \
      -e "s/^story=.*/story=$STORY/" \
      "$MARKDOWN"
    [ -z "$PREV_MARKDOWN" ] || {
      sed -i \
        -e "s%^prev=.*%prev=$PREV_CHAPTER/$PREV_STORY/%" \
        -e "s%^prev-title=.*%prev-title=$PREV_TITLE%" \
        "$MARKDOWN"
      sed -i \
        -e "s%^next=.*%next=$CHAPTER/$STORY/%" \
        -e "s%^next-title=.*%next-title=$TITLE%" \
        "$PREV_MARKDOWN"
    }
    PREV_CHAPTER="$CHAPTER"
    PREV_STORY="$STORY"
    PREV_TITLE="$TITLE"
    PREV_MARKDOWN="$MARKDOWN"
  done
}

# End libexec/fix-markdown
