#!/bin/bash
# Begin libexec/place-js

#---
## Place JavaScript files to destination directory
## @Globals PROJECT_HOME_DIR project home directory
#---
function place-js() {
  local SOURCE_DIR="${SOURCE_DIR:="$PROJECT_HOME_DIR/src"}"
  local SOURCE_JS_DIR="${SOURCE_JS_DIR:="$SOURCE_DIR/js"}"
  local DEST_DIR="${DEST_DIR:="$PROJECT_HOME_DIR/dest"}"
  local DEST_JS_DIR="${DEST_JS_DIR:="$DEST_DIR/js"}"
  local PIDS
  [ -d "$DEST_JS_DIR" ] || mkdir -p "$DEST_JS_DIR"
  awk '/^http.*\.js$/' "$PROJECT_HOME_DIR/share/downloads" |
  while read URL
  do
    local JS="${URL##*/}"
    curl -Lso "$DEST_JS_DIR/$JS" "$URL" &
    PIDS="$PIDS${PIDS:+ }$!"
    grep -sq '^jquery-.*\.js$' <<< "$JS" && ln -sfn "$JS" "$DEST_JS_DIR/jquery.js"
  done
  [ -z "$(ls "$SOURCE_JS_DIR"/*.js 2> /dev/null)" ] || cp -a "$SOURCE_JS_DIR"/*.js "$DEST_JS_DIR/"
  [ -z "$PIDS" ] || wait $PIDS
}

# End libexec/place-js
